#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"
REPO_NAME=hazelcast-desktop

if [ "$HELP" == "true" ]; then
cat <<EOF

SYNOPSIS
   ./$EXECUTABLE [-clean] [-?]

   Builds the perf_test 'factory' environment for the workspace. It downloads
   the dependencies and places them in the following workspace lib directory.

   $PADOGRID_WORKSPACE/lib

OPTIONS
   -clean
             Cleans up the build files after the build completes.

Default: ./$EXECUTABLE

EOF
   exit
fi

pushd $APP_DIR > /dev/null
mvn install
popd > /dev/null

cp $APP_DIR/lib/* $PADOGRID_WORKSPACE/lib/

# Remove the build files if the -clean option is specified.
if [ "$CLEAN" == "true" ]; then
   rm -rf $APP_DIR/lib
fi

#
# Display build information
#
cat <<EOF

Workspace: $PADOGRID_WORKSPACE

Downloaded the required library files into the following directory.

   $PADOGRID_WORKSPACE/lib

CLASSPATH includes the above directory for all apps and clusters running under
this workspace. The downloaded files allow you to run the following add-on(s):

   MapStorePkDbImpl - A Hibernate-driven DB store for primary key based entity objects

See ../README.md for configuring the avove add-on(s).

EOF
